name: Test
run-name: "${{ github.workflow }} - ${{ github.triggering_actor }} - Branch: ${{ github.ref_name }}"

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.8","3.9","3.10","3.11","3.12" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v9
      - name: install project
        run: poetry install
      - name: pylint
        run: poetry run pylint src
      - name: mypy
        run: poetry run mypy src
      - name: test
        run: poetry run pytest --tb=short --junitxml=result.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: result.xml
          summary: true
          fail-on-empty: true
          title: Test results
