name: Pull request
run-name: "PR: ${{ github.workflow }} - ${{ github.triggering_actor }} - Branch: ${{ github.ref_name }}"

on: [pull_request]

jobs:

  verify-housekeeping:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: verify version changed
        run: |
          output=`git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --unified=0 -- pyproject.toml`
          echo "OUTPUT is:"
          echo "$output"
          vdiff=`echo "$output"|egrep "\+version = \"[0-9]+\.[0-9]+\.[0-9]+\""||true`
          echo "Version diff is: ${vdiff}"
          if [ -n "$vdiff" ]; then
            echo "Version has changed, looks ok"
            vdiff=`echo $vdiff|egrep -o "[0-9]+\.[0-9]+\.[0-9]+"`
            echo "version is: $vdiff"
            echo "PACKAGE_VERSION=$vdiff">> $GITHUB_ENV
          else
            echo "version is not changed, please check pyproject.toml"
            exit 1
          fi
      - name: verify release notes added
        run: |
          output=`git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --unified=0 -- release-notes.md`
          release_notes_diff=`echo "$output" |grep "# version ${PACKAGE_VERSION}"||true`
          echo "release notes diff: $release_notes_diff"
          if [ -n "$release_notes_diff" ]; then
            echo "Version changes documented"
          else
            echo "Didn't find release notes, please describe your changes in release-notes.md"
            exit 1
          fi

